FROM smartbear/ready-api-soapui-testrunner:latest
RUN mkdir -p $PROJECT_FOLDER && \
   echo "$PROJECT_FOLDER"
COPY ./ $PROJECT_FOLDER

ARG COMMAND_LINE
RUN echo "COMMAND_LINE"

ARG SUITENAME
RUN echo "SUITENAME"
ARG LOADFROMJSON
RUN echo "LOADFROMJSON"
ARG TAGS
RUN echo "TAGS"

ADD /ext $READYAPI_FOLDER/bin/ext
ADD /scripts $PROJECT_FOLDER/$SUITENAME/scripts
RUN echo $PROJECT_FOLDER/$SUITENAME/scripts
WORKDIR $PROJECT_FOLDER
RUN echo "$PROJECT_FOLDER"
