SELECT HM.INITIATORBANKID,HM.CUSTOMERID,HM.AGREEMENTID,HM.INITIATORID,HP.DEBETACCOUNTNO,HM.MESSAGEID FROM HST_MESSAGE HM INNER JOIN HST_PAYMENTINFO HP ON HM.MESSAGEID = HP.FK_MESSAGEID
WHERE HM.INITIATORBANKID='4201' AND HM.MARKETTYPE = 'BM' ORDER BY MESSAGEID DESC FETCH FIRST 1 ROW ONLY

;--=============================================================================================================================
SELECT CUSTOMERID,ACCOUNTNUMBER,CURRENCY,CUSTOMERTYPE FROM V_AUTHORISATION WHERE ROLETYPE='EIER' AND CUSTBANKID = 35803100 AND CURRENCY = 'EUR'  AND ROWNUM = 1

;--=============================================================================================================================
SELECT CUSTOMERID,ACCOUNTNUMBER,CURRENCY,CUSTOMERTYPE FROM V_AUTHORISATION WHERE ROLETYPE='EIER'  AND CUSTBANKID = 35803100 AND CURRENCY = 'NOK'  AND ROWNUM = 1
;
SELECT * FROM V_AUTH_USERINFO;
SELECT AGREEMENTID,ACCOUNTNUMBER,FIRSTNAME,CURRENCYCODE,CHANNEL FROM V_AUTH_USERINFO WHERE BANKORGID='4201' AND LENGTH(AGREEMENTID)='11' AND MARKETTYPE = 'PM' AND FIRSTNAME IS NOT NULL AND ROWNUM=1;