SELECT * FROM EINVOICE_CUSTOMER_INFO WHERE CUSTOMERAGREEMENTID IN ('797614','180952') ORDER BY NEXT_SYNC_TIME DESC;--1340;1360
UPDATE EINVOICE_CUSTOMER_INFO SET SYNC_END_TIME = SYSDATE + 1/24, NEXT_SYNC_TIME = SYSDATE, SYNC_STATUS = 'QUEUED' WHERE CUSTOMERAGREEMENTID IN ('180952');
UPDATE EINVOICE_CUSTOMER_INFO SET SYNC_END_TIME = SYSDATE + 1/24, NEXT_SYNC_TIME = SYSDATE, SYNC_STATUS = 'QUEUED' WHERE CUSTOMERAGREEMENTID IN ('797614');
COMMIT;
--====================================================================================================================================
SELECT * FROM V_PAYMENT_OVERVIEW_TEST WHERE MESSAGEIDENTIFICATION LIKE 'B2B%' ;--and TRANSACTIONSID > '812955';
--====================================================================================================================================
SELECT V.BANKORGID,V.MARKETTYPE,V.AGREEMENTID,A.CUSTOMERID,V.USERID,V.CHANNEL,V.ACCOUNTNUMBER,V.CURRENCYCODE,V.ACCOUNTTYPENAME,V.BIC,V.APPROVALLIMIT,
V.REGISTERLIMIT,V.TRANSACTIONLIMIT,V.MONTHLYLIMIT,V.FIRSTNAME,V.LASTNAME,E.SYNC_STATUS,E.LAST_SYNC_RESULT,E.ACTIVE_FOR_PROCESSING,V.ACCOUNTROLENAME 
FROM V_AUTH_USERINFO V LEFT OUTER JOIN AUTH_USERAGREEMENT A ON V.AGREEMENTID = A.AGREEMENTID LEFT OUTER JOIN EINVOICE_CUSTOMER_INFO E 
ON E.CUSTOMERAGREEMENTID=A.AGREEMENTID AND E.CUSTOMERAGREEMENTID=V.AGREEMENTID WHERE V.BANKORGID ='3625' AND V.AGREEMENTID IN ('797614','180952');
--====================================================================================================================================
SELECT S.*,A.* FROM STATUSREASON S, STATUSREASON_ADDT_INF A WHERE S.STATUSREASONID = A.FK_STATUSREASONID ORDER BY STATUSREASONID DESC;
SELECT * FROM STATUSREASON_ADDT_INF ORDER BY FK_STATUSREASONID DESC;