SELECT L.LOG_ID, L.BANK_ORG_ID, T.CATEGORY, T.SUBCATEGORY, T.EVENT_NAME, L.EVENT_STATUS, L.USER_ID,L.USER_TYPE, L.LOGGEDBYSYSTEM, L.BUSINESSKEY, 
L.CATEGORY_ID, L.ACCOUNT_NUMBER, T.EVENT_TYPE_ID, L.EVENT_TIME, T.ACCESS_LEVEL, L.USERNAME, L.LOGREF, L.INFORMATION, L.SOURCE_APPLICATION
FROM EVENT_LOG L, EVENT_TYPE T WHERE 1=1 
AND L.FK_EVENT_TYPE_ID=T.EVENT_TYPE_ID 
--AND T.CATEGORY IN ('STANDING_ORDER')  -- 'PAYMENT','MESSAGE','STANDING_ORDER'
--AND T.SUBCATEGORY IN ('STANDING_ORDER')
ORDER BY L.LOG_ID DESC
;
SELECT DISTINCT EVENT_NAME FROM EVENT_TYPE WHERE CATEGORY = 'STANDING_ORDER';
SELECT DISTINCT SUBCATEGORY FROM EVENT_TYPE;