SELECT T.TRANSACTIONSID,T.PAYMENTTYPE,M.INITIATORBANKID,T.PAYMENTSTATUS,T.FK_PROCESSINGLINEID,P.PAYMENTINFOID,M.MESSAGEID, M.MARKETTYPE,TO_CHAR(M.CREATIONDATETIME,'yyyy-mm-dd hh24:mi:ss') CREATEDDATE,T.CONTRACTID,
TO_CHAR(P.REQUESTEDEXECUTIONDATE, 'yyyy-mm-dd hh24:mi:ss') REQEXECDATE,TO_CHAR(T.RELEASEDATE, 'yyyy-mm-dd hh24:mi:ss') RELEASEDATE,T.STATUSCHANGETIME, DEBTOR_ACCOUNT.OTHER_ID AS DEBTACC, T.DEBIT_BOOKING_ID, 
SE.BOOKINGDATE,T.PAYMENT_REF,M.MESSAGEIDENTIFICATION,T.ENDTOENDID,T.CREDITTEXTCODE,M.INITIATORID,M.AGREEMENTID,M.CUSTOMER_TYPE, M.ORIGINALFORMAT, P.CATEGORYPURPOSECODE,T.PAYMENTORDERDATE,T.CREDITAMOUNTAMT,T.CREDITAMOUNTCCY,
T.EQUIVALENTAMOUNT AS EQAMT,T.EQUIVALENTAMOUNT_CCYOFTRF AS EQAMTTRACCY,T.EQUIVALENTAMOUNTCCY AS EQAMCCY,T.INSTRUCTEDAMOUNT, T.INSTRUCTEDAMOUNTCCY,T.DEBITCOUNTERVALUEAMT,T.MARKETPRODUCTCHARGEAMT,T.RISKSTATUS,
DEBTOR_PARTY.PRVTID_OTHER_ID AS DEBTORSSN,DEBTOR_PARTY.NAME AS DEBTORNAME,DEBTOR_PARTY.POSTALADDRESSID,DEBTOR_PARTY.ADDRESSLINE1,DEBTOR_PARTY.ADDRESSLINE2,DEBTOR_PARTY.ADDRESSLINE3,DEBTOR_PARTY.ADDRESSLINE4,
DEBTOR_PARTY.POSTCODE,DEBTOR_PARTY.TOWNNAME,DEBTOR_PARTY.COUNTRY,DEBTOR_ACCOUNT.IBAN AS DEBTIBAN,DEBTOR_AGENT.NAME AS DEBTAGENTNAME,DEBTOR_AGENT.BICFI AS DEBTBIC,CREDITOR_PARTY.NAME CREDNAME,T.HIDDEN,T.EXCHANGERATEVALUE,
CREDITOR_PARTY.COUNTRY AS CREDCOUNTRY,CREDIT_ACCOUNT.IBAN AS CREDACCIBAN,CREDIT_ACCOUNT.OTHER_ID AS CREDACCBBAN,CREDITOR_AGENT.BICFI AS CREDAGTBIC,CREDITOR_AGENT.NAME AS CREDAGENTNAME,T.EXCHANGERATE,T.EXCHANGERATETYPE,
CREDITOR_AGENT.MEMBERID CREDMEMBERID,CREDITOR_AGENT.CLEARINGSYSTEMID CREDCLEARID,T.DEBITAMOUNTAMT,T.DEBITAMOUNTCCY,RES.RESERVATIONREFERENCE
FROM HST_TRANSACTIONS T INNER JOIN HST_PAYMENTINFO P ON T.FK_PAYMENTINFOID = P.PAYMENTINFOID INNER JOIN HST_MESSAGE M ON M.MESSAGEID = P.FK_MESSAGEID
LEFT OUTER JOIN AGENT_PAYMENTINFO DEBTOR_AGENT      ON DEBTOR_AGENT.FK_PAYMENTINFOID = P.PAYMENTINFOID AND DEBTOR_AGENT.FK_AGENTTYPEID =3
LEFT OUTER JOIN AGENT_TRANS CREDITOR_AGENT          ON CREDITOR_AGENT.FK_TRANSACTIONSID = T.TRANSACTIONSID AND CREDITOR_AGENT.FK_AGENTTYPEID =2
LEFT OUTER JOIN PARTY_DEBTOR DEBTOR_PARTY           ON DEBTOR_PARTY.FK_PAYMENTINFOID = P.PAYMENTINFOID AND DEBTOR_PARTY.FK_PARTYTYPEID =2
LEFT OUTER JOIN PARTY_CREDITOR CREDITOR_PARTY       ON CREDITOR_PARTY.FK_TRANSACTIONSID= T.TRANSACTIONSID AND CREDITOR_PARTY.FK_PARTYTYPEID =3
LEFT OUTER JOIN ACCOUNT_DEBTOR DEBTOR_ACCOUNT       ON DEBTOR_ACCOUNT.FK_PAYMENTINFOID = P.PAYMENTINFOID AND DEBTOR_ACCOUNT.FK_ACCOUNTTYPEID=1
LEFT OUTER JOIN ACCOUNT_CREDITOR CREDIT_ACCOUNT     ON CREDIT_ACCOUNT.FK_TRANSACTIONSID = T.TRANSACTIONSID AND CREDIT_ACCOUNT.FK_ACCOUNTTYPEID =3
LEFT OUTER JOIN REGULATORYREPORTING REGREP          ON REGREP.FK_TRANSACTIONSID = T.TRANSACTIONSID
LEFT OUTER JOIN REGULATORYREPORTING_DTLS REGREPDET  ON REGREPDET.FK_RGLTRYRPTGID = REGREP.RGLTRYRPTGID
LEFT OUTER JOIN RESERVATION_DETAILS RES             ON RES.FK_TRANSACTIONSID = T.TRANSACTIONSID AND RES.RESERVATION_TYPE ='D'
LEFT OUTER JOIN STATUSREASON S                      ON S.FK_TRANSACTIONID = T.TRANSACTIONSID
LEFT OUTER JOIN SETTLEMENT SE                       ON SE.FK_TRANSACTIONSID = T.TRANSACTIONSID
LEFT OUTER JOIN STATUSREASON_ADDT_INF SA            ON SA.FK_STATUSREASONID = S.STATUSREASONID
WHERE 1=1 --AND M.INITIATORBANKID IN ('4201','3709')
AND T.ENDTOENDID LIKE ('Batch%')
AND TRUNC(M.CREATIONDATETIME) > TRUNC(SYSDATE-2)
--AND T.TRANSACTIONSID IN ('366575')
ORDER BY PAYMENTSTATUS DESC,T.TRANSACTIONSID DESC;
--AND T.PAYMENTSTATUS IN ('RFPE')  --'VALI','TBAP','TBVE','RFCA','','','','',
--AND M.MARKETTYPE='BM'
--AND T.PAYMENTTYPE ='UNDE'
--AND T.TRANSACTIONSID LIKE ('35621%')
--AND MESSAGEID IN ('2865300')
--AND T.FK_PROCESSINGLINEID = 1
--AND P.PMTINFOID='420341365'
--AND P.PMTINFOID='20282'
--AND T.DEBIT_BOOKING_ID = '14946470000'
--AND T.INSTRUCTEDAMOUNT=1
--AND T.PAYMENTSTATUS <>('COMP')
--AND S.CODE IS NULL
--AND T.CREDITTEXTCODE =521
--AND M.AGREEMENTID IN( '402801')
--AND TRUNC(P.REQUESTEDEXECUTIONDATE)= TO_DATE('2018-05-29', 'yyyy-mm-dd')
--AND TRUNC(P.RELEASEDATE)= TO_DATE('2017-11-15', 'yyyy-mm-dd')
--AND TRUNC(T.STATUSCHANGETIME)< TRUNC(SYSDATE-360) AND TRUNC(T.STATUSCHANGETIME)< TRUNC(SYSDATE-300)
--AND TRUNC(T.STATUSCHANGETIME)= TO_DATE('2018-06-12', 'yyyy-mm-dd')
--AND TRUNC(T.STATUSCHANGETIME)< TO_DATE('2018-06-11', 'yyyy-mm-dd') AND TRUNC(T.STATUSCHANGETIME)> TO_DATE('2018-04-15', 'yyyy-mm-dd')
--AND M.INITIATORID=362440
--AND S.SOURCESYSTEM ='FTSS'
--AND P.SERVICELEVEL ='EINV'
--AND M.CUSTOMER_TYPE ='NOR_STATE_CORP'
--AND T.EXCHANGERATE IS NOT NULL
--AND T.EXCHANGERATETYPE IS NOT NULL
--AND ORIGINALFORMAT = 'PREL'
--AND ORIGINALFORMAT LIKE 'S%'
--AND P.PAYMENTMETHOD='CHK'
--AND DEBTOR_ACCOUNT.OTHER_ID IN('42024874375')
--AND CREDIT_ACCOUNT.OTHER_ID IN('52010691990')
--AND DEBTOR_ACCOUNT.CURRENCY != 'NOK'
--AND DEBTOR_ACCOUNT.OTHER_ID IN
-- ( SELECT ACC.ACCOUNTNUMBER FROM AUTH_USERAGREEMENT AG, AUTH_USER U, AUTH_ACCOUNT ACC, AUTH_ACCOUNTTOACCOUNTROLE ROLE, AUTH_ACCOUNTROLE ROLES, AUTH_USERTOCHANNEL UC, AUTH_CHANNEL C
--  WHERE AG.AUTHUSERAGREEMENTID = U.FK_AUTHUSERAGREEMENTID AND ACC.FK_AUTHUSERID = U.AUTHUSERID AND ROLE.FK_AUTHACCOUNTID = ACC.AUTHACCOUNTID AND ROLE.FK_AUTHACCOUNTROLEID = ROLES.AUTHACCOUNTROLEID
--  AND UC.FK_AUTHUSERID = U.AUTHUSERID AND UC.FK_AUTHCHANNELID = C.AUTHCHANNELID AND AGREEMENTID='130652' AND USERID='362414' AND BANKORGID='4201')
--AND DEBTOR_PARTY.PRVTID_OTHER_ID IN ('96500901958')
--AND DEBTOR_ACCOUNT.OTHER_ID IN ('44762024389','44762024397','44762024397')
--AND T.TRANSACTIONSID IN (SELECT FK_TRANSACTIONID FROM STATUSREASON WHERE CODE NOT IN ('DS02', 'STLF', 'STUS'))
--AND DEBTOR_PARTY.NAME IS NULL
--AND DEBTOR_POSTAL.ADDRESSLINE1 IS NULL AND P.RELEASEDATE=SYSDATE
--AND DEBTOR_POSTAL.POSTCODE IS NULL AND P.RELEASEDATE=SYSDATE
--AND CREDAGENT_POSTAL.COUNTRY='SE' AND CREDITOR_AGENT.BICFI IS NULL
--AND INSTRUCTEDAMOUNT=0.25
--AND INSTRUCTEDAMOUNT>2 AND INSTRUCTEDAMOUNT<12
--AND P.CATEGORYPURPOSECODE ='IDCP'
--AND S.CODE NOT IN ('RR09','AC03','AM04','DS02')
--AND S.CODE NOT IN ('AM04','AC03','AC10','AC06','AC02','TA01','AM11')
--ORDER BY T.PAYMENTSTATUS DESC, T.TRANSACTIONSID DESC;
--ORDER BY P.REQUESTEDEXECUTIONDATE, M.CREATIONDATETIME;
--GROUP BY CODE;