/*
	CAMT.055 PWH Tables
*/
	SELECT * FROM CANCELLATION_APPROVER;
	SELECT * FROM CANCELLATION_MESSAGE;
	SELECT * FROM CANCELLATION_MSG_INSTR_AMT;
	SELECT * FROM CANCELLATION_PAYMENTINFO;
	SELECT * FROM CANCELLATION_PMTINFO_INSTR_AMT;
	SELECT * FROM CANCELLATION_REQUEST;
	SELECT * FROM CANCELLATION_TRANSACTION;
/*
	To Delete NULL values from DB which causes error "Amount Cannot Be Null PIDOM-6063"
*/
DELETE FROM CANCELLATION_REQUEST WHERE CANCELREQUESTID  IN
	(SELECT FK_CANCELLATIONREQUESTID FROM CANCELLATION_MESSAGE WHERE CANCELLATIONMESSAGEID IN
		(select FK_CANCELLATIONMESSAGEID from CANCELLATION_PAYMENTINFO where CANCELPAYMENTINFOID IN
			(select FK_CANCELPAYMENTINFOID from cancellation_pmtinfo_instr_amt where SUMINSTRUCTEDAMOUNT is null)));
