/*
	To Find Constraints & Primary key in child tables
*/
SELECT OWNER,CONSTRAINT_NAME,CONSTRAINT_TYPE,TABLE_NAME,R_OWNER,R_CONSTRAINT_NAME
    FROM ALL_CONSTRAINTS WHERE 1=1 AND CONSTRAINT_TYPE='R' AND R_CONSTRAINT_NAME IN 
		(SELECT CONSTRAINT_NAME FROM ALL_CONSTRAINTS WHERE CONSTRAINT_TYPE IN ('P','U') AND TABLE_NAME='STO_AGREEMENT')
;