SELECT * FROM V_DHUB_SO_AGREEMENT ORDER BY AGREEMENTID DESC;
SELECT COUNT(*) AS TOTAL FROM V_DHUB_SO_AGREEMENT;

SELECT FILE_SEQNO, BANK_ID, TABLENAME, EXTRACT_DATE FROM STO_DHUBFILE ORDER BY EXTRACT_DATE DESC;