--=============================================================================
-- PWH_VIEW
    SELECT V.MESSAGEID,V.TRANSACTIONSID, T.PAYMENT_REF,V.DEBETACCOUNTNO,V.CREDITOR_IBAN,V.PAYMENTTYPE,V.PAYMENTSTATUS,V.RISKSTATUS,SCA.EVENT_SOURCE,SCA.SCA_PERFORMED,SCA.SCA_LAST_PERFORMED,SCA.EXEMPTION_TYPE,V.INITIATORBANKID,
    V.PROCESSINGBANKORGID,V.MARKETTYPE,V.INSTRUCTEDAMOUNT,SCA.PK_EVENTLOG_ID
    FROM V_PAYMENT_OVERVIEW_TEST V, SCA_EVENTLOG SCA, TRANSACTIONS T WHERE SCA.FK_TRANSACTIONSID = V.TRANSACTIONSID AND T.TRANSACTIONSID = V.TRANSACTIONSID
--    AND INITIATORBANKID IN (4201)
--    AND V.MARKETTYPE = 'BM'
--    AND RISKSTATUS IS NOT NULL --
--    AND V.RISKSTATUS IN ( 'PFIP','EFIP','CFIP')
--    AND RISKSTATUS IN ( 'AFIP','AEFP','ACFP')
ORDER BY V.TRANSACTIONSID DESC, SCA.PK_EVENTLOG_ID DESC
;--=============================================================================
--SCA_DATA_STORE_PWH
    SELECT * FROM SCA_EVENTLOG ORDER BY PK_EVENTLOG_ID DESC;
    SELECT * FROM HST_SCA_EVENTLOG ORDER BY PK_EVENTLOG_ID DESC;
    SELECT * FROM HST_TRANSACTIONS ORDER BY TRANSACTIONSID DESC
;--=============================================================================
--FRAUD_CRITERIA_RBS_BANK_SCHEMA
    SELECT * FROM BANK.FRAUD_KRITERIER;
    SELECT * FROM BANK.FRAUD_ADRESSER;
    INSERT INTO BANK.FRAUD_ADRESSER VALUES ('10','4201','SANATH.KUMAR.DHARMASTHALA@EVRY.COM','','SANATH','');
    DELETE FROM BANK.FRAUD_ADRESSER WHERE SEKVENSNR IN ('10','11')
;--=============================================================================
SELECT * FROM HST_TRANSACTIONS ORDER BY TRANSACTIONSID DESC;