SELECT * FROM HST_TRANSACTIONS ORDER BY TRANSACTIONSID DESC;
SELECT * FROM HST_PAYMENTINFO ORDER BY PAYMENTINFOID DESC;
SELECT * FROM HST_MESSAGE ORDER BY MESSAGEID DESC;
SELECT * FROM HST_RESERVATION_DETAILS ORDER BY RESERVATIONDETAILSID DESC;
SELECT * FROM HST_SETTLEMENT ORDER BY SETTLEMENTID DESC;