--MIGRATE BANK
SELECT * FROM BANK.BR1 WHERE INSTITUTION_CODE = '3240';
SELECT DISTINCT INSTITUTION_CODE FROM BANK.BR1 WHERE MIGRERINGSSTATUS = 'IN_PROCESS';
UPDATE BANK.BR1 SET MIGRERINGSSTATUS = 'IN_PROCESS' WHERE INSTITUTION_CODE = '3240';
--------------------------------------------------------------------------------------------------------
--MIGRATE CUSTOMER
--SELECT BRUKER_KUNDENR, INSTITUTION_CODE, MIGRATION_DATE FROM AUT.AU1 WHERE INSTITUTION_CODE = '3240' 
SELECT * FROM AUT.AU1 WHERE INSTITUTION_CODE = '4201' AND MIGRATION_DATE IS NULL and BRUKER_KUNDENR LIKE '00809093050%'
--    AND BRUKER_KUNDENR IN ('14107005111','26067412051','26107019579','20062511738');
;
UPDATE AUT.AU1 SET MIGRATION_DATE = TO_DATE('2020-12-21','yyyy-mm-dd') WHERE INSTITUTION_CODE = '3240'
    AND BRUKER_KUNDENR IN ('20062511738');
--------------------------------------------------------------------------------------------------------
--PWH CUSTOMER INFORMATION
SELECT BANKORGID,USERID,ACCOUNTNUMBER,ACCOUNTROLENAME FROM V_AUTH_USERINFO WHERE BANKORGID = '3240' AND CHANNEL = 'INT'
--    AND USERID IN ('26107019579')
    AND ACCOUNTNUMBER IN ('32404500642')
    ORDER BY USERID,ACCOUNTNUMBER,ACCOUNTROLENAME;
--------------------------------------------------------------------------------------------------------
--PAYS PAYMENTS
SELECT * FROM FORFALL.BK1 WHERE INSTITUTION_CODE = '4201' AND KUNDENR = '0%';