SELECT * FROM MONITOR_ONLINE_PERFORMANCE --WHERE LOGTIME > SYSDATE - (10/24/60)
ORDER BY LOGTIME DESC;

SELECT * FROM MONITOR_BATCH_PERFORMANCE WHERE LOGTIME > SYSDATE - 2 --(10/24/60) 
ORDER BY LOGTIME DESC;