SELECT * FROM PI_ALERT WHERE 1=1
--AND ALERTID > '1200'
--AND APP IN ('EOS-PIN-D14I1')
--AND BANKID IN ('4201')
--AND USERID IN ('20107611879')
--AND FAILURETYPE IN ('FRAUD_IN_PAYMENT')
--AND SEVERITY IN ('WARNING')
--AND LOGREF LIKE '600685%'
--AND TRUNC(OCCURRED) > '30-JUL-20'
--AND TRUNC(NOTIFIED) > '30-JUL-20'
--AND STACKTRACE IS NULL
--AND MESSAGE IS NOT NULL
ORDER BY ALERTID DESC;

SELECT DISTINCT SEVERITY FROM PI_ALERT;