SELECT * FROM PI_JOB_INSTANCE JI, PI_JOB_EXECUTION JE, PI_JOB_EXECUTION_CONTEXT JEC, PI_JOB_EXECUTION_PARAMS JEP, PI_STEP_EXECUTION SE, 
PI_STEP_EXECUTION_CONTEXT SEC WHERE 1=1 AND JI.JOB_INSTANCE_ID=JE.JOB_INSTANCE_ID AND JE.JOB_EXECUTION_ID=JEC.JOB_EXECUTION_ID
AND JE.JOB_EXECUTION_ID=JEP.JOB_EXECUTION_ID AND JE.JOB_EXECUTION_ID=SE.JOB_EXECUTION_ID AND SE.STEP_EXECUTION_ID=SEC.STEP_EXECUTION_ID
--AND JI.JOB_NAME IN ('generateSOPaymentsJob','capitalizationJob','reservationResponseJob','porReservationJob','porReservationJob')
--AND JI.JOB_NAME='generateSOPaymentsJob'
--AND JE.JOB_EXECUTION_ID='4004'
--AND JI.JOB_INSTANCE_ID = '3803'
--AND JEP.KEY_NAME='soType'
--AND JE.CREATE_TIME > '03-MAR-21'
ORDER BY SE.STEP_EXECUTION_ID DESC
;
SELECT * FROM PI_JOB_EXECUTION ORDER BY JOB_EXECUTION_ID DESC, JOB_INSTANCE_ID;
SELECT * FROM PI_JOB_EXECUTION_CONTEXT ORDER BY JOB_EXECUTION_ID DESC;
SELECT * FROM PI_JOB_EXECUTION_PARAMS ORDER BY JOB_EXECUTION_ID DESC;
SELECT * FROM PI_JOB_INSTANCE ORDER BY JOB_INSTANCE_ID DESC;
SELECT * FROM PI_STEP_EXECUTION ORDER BY STEP_EXECUTION_ID DESC, JOB_EXECUTION_ID;
SELECT * FROM PI_STEP_EXECUTION_CONTEXT ORDER BY STEP_EXECUTION_ID DESC;