SELECT * FROM CTL_BATCH_RUN_SCHEMA WHERE BATCH_NAME IN ('POR','POR3') --POR, POR3
--  AND SCHEMA_NAME IN ('POR_BATCH_1','POR_BATCH_2','POR_BATCH_3') AND STATUS IN ('FREE')
;--===============================================================================================
UPDATE CTL_BATCH_RUN_SCHEMA SET STATUS='FREE' WHERE BATCH_NAME LIKE 'POR%' AND SCHEMA_NAME='POR_BATCH_1'
;--===============================================================================================
--SELECT * FROM CTL_POR_NONMIGRATED_BANKS ORDER BY INITIATORBANKID;
SELECT * FROM CTL_BATCH_RUN_SCHEMA;
SELECT * FROM POR_BATCH_FILE_LOG ORDER BY FK_DUEDATEPROCESSID DESC;
--===============================================================================================
SELECT * FROM PI_JOB_EXECUTION ORDER BY JOB_EXECUTION_ID DESC, JOB_INSTANCE_ID;
SELECT * FROM PI_JOB_EXECUTION_CONTEXT ORDER BY JOB_EXECUTION_ID DESC;
SELECT * FROM PI_JOB_EXECUTION_PARAMS ORDER BY JOB_EXECUTION_ID DESC;
SELECT * FROM PI_JOB_INSTANCE ORDER BY JOB_INSTANCE_ID DESC;
SELECT * FROM PI_STEP_EXECUTION ORDER BY STEP_EXECUTION_ID DESC, JOB_EXECUTION_ID;
SELECT * FROM PI_STEP_EXECUTION_CONTEXT ORDER BY STEP_EXECUTION_ID DESC;
--===============================================================================================
SELECT DISTINCT KEY_NAME FROM PI_JOB_EXECUTION_PARAMS;