--==============================================================================
WITH COUNT_D AS (SELECT AGREEMENTID,COUNT(0) DOM_COUNT FROM PDC_PREDEFINEDCREDITOR WHERE TYPE='DOM' GROUP BY AGREEMENTID),
     COUNT_I AS (SELECT AGREEMENTID,COUNT(0) INT_COUNT FROM PDC_PREDEFINEDCREDITOR WHERE TYPE='INT' GROUP BY AGREEMENTID),
     COUNT_T AS (SELECT AGREEMENTID,COUNT(0) TOT_COUNT FROM PDC_PREDEFINEDCREDITOR GROUP BY AGREEMENTID HAVING COUNT(0)>1000)
SELECT COUNT_T.AGREEMENTID,DOM_COUNT,INT_COUNT,TOT_COUNT FROM COUNT_D,COUNT_I,COUNT_T
WHERE COUNT_T.AGREEMENTID=COUNT_D.AGREEMENTID AND COUNT_T.AGREEMENTID=COUNT_I.AGREEMENTID
ORDER BY 4 DESC
;
--==============================================================================