--====================================================================
--SEARCH AND DELETE THE TRANSACTIONS ID FROM PWHTTH
SELECT * FROM PWHTTH WHERE TRANSACTIONSID LIKE '304224' ORDER BY TRANSACTIONSID DESC;
DELETE FROM PWHTTH WHERE TRANSACTIONSID LIKE '304224';
--====================================================================
--SEARCH THE PWH TO RBS COPY DATA - FORFALL
SELECT LOPENR,INSTITUTION_CODE,KONTONR,BETALORADATO,TRANSNR,SEKVENSNR,FORFORADATO,BMKONTONR,BELOP,KID,KUNDENR,AVSENDERID,AJARKREF,PRODUKTID FROM BK21 WHERE 1=1
AND INSTITUTION_CODE='4201' 
--AND KONTONR='42024109660' 
--AND LOPENR LIKE '304224' 
;--====================================================================
--SEARCH AND UPDATE RELEASE DATES FROM TRANSACTIONS TABLE
SELECT * FROM TRANSACTIONS WHERE TRANSACTIONSID LIKE '2047%' AND ENDTOENDID LIKE '600685_%' AND INSTRUCTEDAMOUNT='1.52' ORDER BY TRANSACTIONSID DESC;

UPDATE TRANSACTIONS SET RELEASEDATE=TRUNC(SYSDATE)              WHERE TRANSACTIONSID LIKE '2047%' AND ENDTOENDID LIKE '600685_%' AND INSTRUCTEDAMOUNT='1.52';
UPDATE TRANSACTIONS SET REQUESTEDEXECUTIONDATE=TRUNC(SYSDATE)   WHERE TRANSACTIONSID LIKE '2047%' AND ENDTOENDID LIKE '600685_%' AND INSTRUCTEDAMOUNT='1.52';
--====================================================================