-- RBS_TO_PWH_MIGRATION_AUT_SCHEMA
  SELECT * FROM V_AUT_AU1; --WHERE BRUKER_KUNDENR IN ('09026238398','05045130349');
  SELECT * FROM V_AUT_AU3;
  SELECT * FROM V_AUT_AU6;
  SELECT * FROM V_AUT_AU9;
  SELECT * FROM V_AUT_AU20;
  SELECT * FROM V_AUT_AU23;
--  SELECT * FROM AUT.AU9;
--  SELECT * FROM AUT.AU1 WHERE BRUKER_KUNDENR IN ('01089500199');
--  UPDATE AUT.AU1 SET MIGRATION_DATE = TO_DATE('2019-10-23','YYYY-MM-DD') WHERE BRUKER_KUNDENR IN ('05045130349');
------------------------------------------------------------------------------------------
-- RBS_ACCUMULATION_FORFALL_SCHEMA
    SELECT * FROM FORFALL.BK31 WHERE BRUKERID LIKE '%5659102' ORDER BY PERIODESLUTT;
--    DELETE FROM FORFALL.BK31 WHERE BRUKERID = '00004231911' AND PERIODESLUTT = '31-JUL-20' ;
------------------------------------------------------------------------------------------
-- KID_AVTALE_SCHEMA
    SELECT * FROM AVTALE.VOC_HENT_GJELDENDE WHERE KONTONR LIKE '3625%';
--    SELECT * FROM AVTALE.OC1 WHERE KONTONR IN --('32017049312');	-- SELECT * FROM AVTALE.OC2; --SELECT * FROM AVTALE.OC3;
------------------------------------------------------------------------------------------
-- FRAUD_CRITERIA_RBS_BANK_SCHEMA
    SELECT * FROM BANK.FRAUD_KRITERIER;
    SELECT * FROM BANK.FRAUD_ADRESSER;
--    INSERT INTO BANK.FRAUD_ADRESSER VALUES ('10','4201','SANATH.KUMAR.DHARMASTHALA@EVRY.COM','','SANATH','');
--    DELETE FROM BANK.FRAUD_ADRESSER WHERE SEKVENSNR IN ('10','11');
------------------------------------------------------------------------------------------
-- RBS_?_FORFALL_SCHEMA
    SELECT * FROM RISK.RISK_CUSTOMER_COUNTRY;
--    INSERT INTO RISK.RISK_CUSTOMER_COUNTRY
    SELECT * FROM RISK.RISK_BANK;
    UPDATE RISK.RISK_BANK SET MIN_AMOUNT_TRX_PM='20' WHERE ORGID='9055';
    UPDATE RISK.RISK_BANK SET MIN_AMOUNT_TRX_BM='15' WHERE ORGID='9055';
------------------------------------------------------------------------------------------
-- RBS_?_FORFALL_SCHEMA
    SELECT * FROM BK12 WHERE INSTITUTION_CODE='2544' ORDER BY FORFORADATO DESC;
------------------------------------------------------------------------------------------
-- PWH TO RBS COMPATIBILITY TESTING - PAYMENT TEST DATA
    SELECT INSTITUTION_CODE,KONTONR,BETALNR,PRODUKTID,KUNDENR,BELOP,AVTALENR,AVTALENR,TRANSNR,LOPENR,SEKVENSNR,FORFORADATO 
    FROM FORFALL.BK1 WHERE INSTITUTION_CODE = '4201' AND KUNDENR LIKE '00%' AND PRODUKTID IN ('BES','ITR','INT') 
--    AND KONTONR = '44250167498' --AND BETALNR ='206'
    ;
    SELECT * FROM FORFALL.BK1 WHERE INSTITUTION_CODE = '4201'; --AND KUNDENR LIKE ('00%') AND PRODUKTID = 'INT';
--    86744250167498
;------------------------------------------------------------------------------------------
SELECT * FROM FORFALL.BK21 WHERE BETALORADATO > '13-JUN-21';
SELECT * FROM FORFALL.BK21 WHERE INSTITUTION_CODE = '4201';
SELECT INSTITUTION_CODE,KONTONR,BETALNR,BETALORADATO,TRANSNR,LOPENR,SEKVENSNR,FORFORADATO,BMKONTONR,KUNDENR,PRODUKTID,BETALINGSTYPE,
KANAL,OPPRORADATO,FAKTURAVALUTASORT FROM FORFALL.BK21 WHERE LOPENR = '1000025835' ;--1000025835 1000023228 1000020744 1000020763