-- For these searches (Transaction search, message search, paymentinfo search and account level search), 
-- The statusreason is fetched from "V_FORFALL_BK1_StatusReason" and additionalinformation is fetched from "V_FORFALL_BK9_AdditionalInformation"
SELECT * FROM PWHDATA.V_FORFALL_BK1; --WHERE TRANSACTIONSID = '-537744350343730'; 
SELECT INSTITUTION_CODE,TRANSACTIONSID,KONTONR,BETALNR,TRANSNR,T_PAYMENTSTATUS,PAYMENTTYPE,STATUSNR,AVSENDERID,PRODUKTID,AGREEMENTTYPE,KID
FROM PWHDATA.V_FORFALL_BK1 WHERE INSTITUTION_CODE = '4201' AND TRANSACTIONSID IN ('-537744350343730','-539944350343730') ORDER BY BETALNR DESC;

SELECT * FROM V_FORFALL_BK9;