SELECT * FROM V_PAYMENT_OVERVIEW_TEST WHERE STATUSCHANGETIME > (SYSDATE - 30/24/60);
----------SELECT * FROM REGULATORYREPORTING;--SELECT * FROM REGULATORYREPORTING_DTLS;--SELECT * FROM REGULATORYREPORTING_DTLS_INFO;
SELECT RR.RGLTRYRPTGID,RRD.RGLTRYRPTGDTLSID,RRDI.RGLTRYRPTGDTLSINFOID,RR.FK_TRANSACTIONSID,RRD.CODE,RRD.INFORMATION,RRDI.LINE_NUMBER,
RRDI.INFORMATION AS INFORMATION_RRDI,RR.DBTCDTREPORTINGIND,RR.AUTHORITY_NAME,RR.AUTHORITY_COUNTRY,RRD.TP,RRD.DT,RRD.COUNTRY,RRD.AMOUNT
FROM REGULATORYREPORTING RR INNER JOIN REGULATORYREPORTING_DTLS RRD ON RR.RGLTRYRPTGID = RRD.FK_RGLTRYRPTGID 
INNER JOIN REGULATORYREPORTING_DTLS_INFO RRDI ON RRD.RGLTRYRPTGDTLSID = RRDI.FK_RGLTRYRPTGDTLSID ORDER BY RR.RGLTRYRPTGID DESC;
----------SELECT * FROM REGULATORYREPORTING_DTLS_IW; --SELECT * FROM HST_REGULATORYREPORTING;--SELECT * FROM HST_REGULATORYREPORTING_DTLS;
SELECT RR.RGLTRYRPTGID,RRD.RGLTRYRPTGDTLSID,RRDI.RGLTRYRPTGDTLSINFOID,RR.FK_TRANSACTIONSID,RRD.CODE,RRD.INFORMATION,RRDI.LINE_NUMBER,
RRDI.INFORMATION AS INFORMATION_RRDI,RR.DBTCDTREPORTINGIND,RR.AUTHORITY_NAME,RR.AUTHORITY_COUNTRY,RRD.TP,RRD.DT,RRD.COUNTRY,RRD.AMOUNT
FROM HST_REGULATORYREPORTING RR INNER JOIN HST_REGULATORYREPORTING_DTLS RRD ON RR.RGLTRYRPTGID = RRD.FK_RGLTRYRPTGID 
INNER JOIN HST_REG_REPORTING_DTLS_INFO RRDI ON RRD.RGLTRYRPTGDTLSID = RRDI.FK_RGLTRYRPTGDTLSID ORDER BY RR.RGLTRYRPTGID DESC;
----------SELECT * FROM HST_REG_REPORTING_DTLS_INFO; --SELECT * FROM REGULATORYREPORTING_DTLS;
SELECT * FROM TRANSACTIONS ORDER BY TRANSACTIONSID DESC;--260771453
SELECT * FROM REGULATORYREPORTING_DTLS;
SELECT * FROM STO_REGULATORY_REPORTING ORDER BY RGLTRYRPTGDTLSINFOID DESC;
SELECT * FROM STO_TRANSACTIONS ORDER BY TRANSACTIONSID DESC;