SELECT * FROM REMITTANCEINFO ORDER BY REMITTANCEINFOID DESC;
SELECT * FROM REMITTANCEINFO_USTRD ORDER BY REMITTANCEINFOUSTRDID DESC;
SELECT * FROM REMITTANCEINFO_STRD ORDER BY REMITTANCEINFOSTRDID DESC;
SELECT * FROM REFERREDDOCINFO ORDER BY FK_REMITTANCEINFOSTRDID DESC;

SELECT RI.REMITTANCEINFOID, RI.FK_TRANSACTIONSID, RIU.REMITTANCEINFOUSTRDID, RI.ISERIPAYMENT, RIU.UNSTRUCTURED, RIS.REMITTANCEINFOSTRDID,
RIS.DUEPAYABLEAMOUNT, RIS.DUEPAYABLEAMOUNTCCY,RIS.CREDITNOTEAMOUNT,RIS.CREDITNOTEAMOUNTCCY,RIS.CREDITORREFINFOCODE,
RIS.CREDITORREFINFOREFERENCE,RIS.REMITTEDAMOUNT,RIS.REMITTEDAMOUNTCCY,RIS.ADDITIONALINFO1,RIS.ADDITIONALINFO2,RIS.ADDITIONALINFO3,
RIS.CREDITORREFERENCEINFOPRTRY FROM REMITTANCEINFO RI INNER JOIN REMITTANCEINFO_USTRD RIU ON RIU.FK_REMITTANCEINFOID = RI.REMITTANCEINFOID
INNER JOIN REMITTANCEINFO_STRD RIS ON RIS.FK_REMITTANCEINFOID = RI.REMITTANCEINFOID --WHERE FK_TRANSACTIONSID IN ('261097149','261098978')
ORDER BY REMITTANCEINFOID DESC;

SELECT RI.REMITTANCEINFOID, RI.FK_TRANSACTIONSID, RIU.REMITTANCEINFOUSTRDID, RI.ISERIPAYMENT, RIU.UNSTRUCTURED, RIS.REMITTANCEINFOSTRDID,
RIS.DUEPAYABLEAMOUNT, RIS.DUEPAYABLEAMOUNTCCY,RIS.CREDITNOTEAMOUNT,RIS.CREDITNOTEAMOUNTCCY,RIS.CREDITORREFINFOCODE,
RIS.CREDITORREFINFOREFERENCE,RIS.REMITTEDAMOUNT,RIS.REMITTEDAMOUNTCCY,RIS.ADDITIONALINFO1,RIS.ADDITIONALINFO2,RIS.ADDITIONALINFO3,
RIS.CREDITORREFERENCEINFOPRTRY FROM HST_REMITTANCEINFO RI INNER JOIN HST_REMITTANCEINFO_USTRD RIU ON 
RIU.FK_REMITTANCEINFOID=RI.REMITTANCEINFOID INNER JOIN HST_REMITTANCEINFO_STRD RIS ON RIS.FK_REMITTANCEINFOID = RI.REMITTANCEINFOID 
ORDER BY REMITTANCEINFOID DESC;