SELECT * FROM V_PAYMENT_OVERVIEW_TEST;
SELECT * FROM HST_TRANSACTIONS ORDER BY TRANSACTIONSID DESC;
--SELECT * FROM HST_SETTLEMENT;     --SELECT * FROM HST_SETTLEMENT_AMOUNT;    --SELECT * FROM SETTLEMENT_AMOUNT_TYPE;

SELECT HS.SETTLEMENTID, HS.ORGID, HS.FK_TRANSACTIONSID, HS.MARKETTYPE, HSA.AMOUNT, HSA.AMOUNTCCY, HS.MSGID, HS.ACCOUNTSERVICEREFERENCE,
HS.BOOKINGDATE, HS.VALUEDATE, HS.REFERENCE , HSA.SETTLEMENTAMOUNTID
FROM HST_SETTLEMENT HS INNER JOIN HST_SETTLEMENT_AMOUNT HSA ON HS.SETTLEMENTID = HSA.FK_SETTLEMENTID ORDER BY HSA.SETTLEMENTAMOUNTID;