/*
	TAKE THE COUNT OF PENDING_DATE & ACTIVE AGREEMENTS IN THE STO_AGREEMENT TABLE
*/
SELECT COUNT(AGREEMENTID) AS SO_PERIODIC_WAIT FROM STO_AGREEMENT
    WHERE STATUS='PENDING_DATE' AND AGREEMENTTYPE='PERIODIC';

SELECT COUNT(AGREEMENTID) AS SO_PERIODIC_ACTIVE FROM STO_AGREEMENT
    WHERE STATUS='ACTIVE' AND AGREEMENTTYPE='PERIODIC';

SELECT COUNT(AGREEMENTID) AS SO_BALANCE_WAIT FROM STO_AGREEMENT
    WHERE STATUS='PENDING_DATE' AND AGREEMENTTYPE='BALANCE';

SELECT COUNT(AGREEMENTID) AS SO_BALANCE_ACTIVE FROM STO_AGREEMENT
    WHERE STATUS='ACTIVE' AND AGREEMENTTYPE='BALANCE';
/*
	TAKE THE LIST OF BANKS WHICH HAS SO IN DB*
*/
SELECT DISTINCT ORG_ID AS ORG_SO_PERIODIC_WAIT FROM STO_AGREEMENT
    WHERE STATUS='PENDING_DATE' AND AGREEMENTTYPE='PERIODIC';
SELECT DISTINCT ORG_ID AS ORG_SO_PERIODIC_ACTIVE FROM STO_AGREEMENT
    WHERE STATUS='ACTIVE' AND AGREEMENTTYPE='PERIODIC';
SELECT DISTINCT ORG_ID AS ORG_SO_BALANCE_WAIT FROM STO_AGREEMENT
    WHERE STATUS='PENDING_DATE' AND AGREEMENTTYPE='BALANCE';
SELECT DISTINCT ORG_ID AS ORG_SO_BALANCE_ACTIVE FROM STO_AGREEMENT
    WHERE STATUS='ACTIVE' AND AGREEMENTTYPE='BALANCE';
Requirement
/*
	NFT RESULT BEFORE FIX - REQUIREMENTS - PIDOM-6427
	Making 100k SO Agreements as
		20% to today
		40% to tomorrow
		20% to 2 Days From Today
		20% to 3 Days From Today
*/
--SET ALL AGREEMENTS TO HAVE SOME COMMON DATE IN NEXT_PAYMENT_DATE FIELD
UPDATE STO_AGREEMENT SET NEXT_PAYMENT_DATE = '01-AUG-2020';
 
--UPDATE FIRST 20% OF THE RECORDS
UPDATE STO_AGREEMENT SET NEXT_PAYMENT_DATE = SYSDATE WHERE ROWNUM <= ((SELECT COUNT(*) FROM STO_AGREEMENT)*0.2);
 
--UPDATE NEXT 40% OF THE RECORDS
UPDATE STO_AGREEMENT SET NEXT_PAYMENT_DATE = SYSDATE+6 WHERE NEXT_PAYMENT_DATE = '01-AUG-2020' AND ROWNUM <= ((SELECT COUNT(*) FROM STO_AGREEMENT)*0.4);
 
--UPDATE NEXT 20% OF THE RECORDS
UPDATE STO_AGREEMENT SET NEXT_PAYMENT_DATE = SYSDATE+7 WHERE NEXT_PAYMENT_DATE  = '01-AUG-2020' AND ROWNUM <= ((SELECT COUNT(*) FROM STO_AGREEMENT)*0.2);
 
--UPDATE LAST 20% OF THE RECORDS
UPDATE STO_AGREEMENT SET NEXT_PAYMENT_DATE = SYSDATE+8 WHERE NEXT_PAYMENT_DATE  = '01-AUG-2020' AND ROWNUM <= ((SELECT COUNT(*) FROM STO_AGREEMENT)*0.2);
 
--UPDATE ALL TRANSACTIONS TABLE AGREEMENT ID VALUES TO UNLINK FROM SO AGREEMENT BY SETTING SOME VALUE AS 1
--THIS MAY TAKE SOME TIME AS THERE ARE MORE TRANSACTIONS.
UPDATE TRANSACTIONS SET AGREEMENTID = 1;
 
--COMMIT ONLY WHEN YOU ARE SURE.
COMMIT;

/*
	This batch is running for 2,5 hours in productions with approximately 200 000 agreements in SO.
	This volume will increase to 1 800 000+ when all banks are merged. We need to get this batch running 10 times better than it is now.
	This is NOT a redesign but a refactor to improve performance both in database and java. Batch should complete within 2 hours when all banks are merged.
		
	Refer Slack: https://evryfs.slack.com/archives/G011MRBAFMJ
		Thats OK, we can take help of DBA to change the due dates.
		First 10k - to have due date starting from "1st day of the month"
		Next 10k -15th day of the month
		like start from seq 10,001 change all due dates to 15 April uuntil 20,000
		This will update like this. Total records in STO_AGREEMENT is 104,185.
*/