SELECT * FROM V_SO_OVERVIEW_TEST WHERE 1=1 --AND AGREEMENTID = 11410
--AND ORG_ID IN ('4201')  AND CREATED_DATE > SYSDATE -1 -- AND AGREEMENTID = 59735 ORDER BY INTERNAL_ID DESC, TRANSACTIONSID DESC;
--AND CREATED_DATE > SYSDATE-1 --  AND STATUS = 'ACTIVE' --  AND AGREEMENTID = '8572' --  AND AGREEMENTACCOUNTNUMBER IN ('42025053081') --418 rows
--AND AGREEMENTTYPE IN ('BALANCE') --AND LIMIT_TYPE='ABOVE'   --  AND CREATED_DATE < SYSDATE-365 --  AND TRANSACTIONSID is null
--  AND PAYMENTSTATUS IN ( 'REJC')   --AND DUE_DATE <= SYSDATE  --  AND PAYMENTSTATUS NOT IN ( 'RFDD','RFCA') --AND DUE_DATE <= SYSDATE
;
SELECT * FROM STO_PAYMENTINFO WHERE FK_AGREEMENT_INTERNAL_ID = 117914;
SELECT * FROM STO_PARTY_DEBTOR WHERE FK_PAYMENTINFOID = 118592;
SELECT * FROM STO_AGREEMENT WHERE AGREEMENTID = 11410;
SELECT * FROM STO_AGREEMENT ORDER BY AGREEMENTID DESC;
SELECT * FROM STO_RECURRENCE_COMPLETED WHERE FK_AGREEMENT_INTERNAL_ID = '1530' ORDER BY FK_AGREEMENT_INTERNAL_ID DESC;
SELECT * FROM STO_AGREEMENT WHERE STATUS = 'VALIDATED';
SELECT count(*) FROM STO_RECURRENCE WHERE FK_AGREEMENT_INTERNAL_ID IN (SELECT INTERNAL_ID FROM STO_AGREEMENT WHERE 1=1
AND TRUNC(CREATED_DATE) < SYSDATE-100);
--AND STATUS = 'VALIDATED');