SELECT * FROM STATUSREASON SR, STATUSREASON_ADDT_INF SA 
WHERE SR.STATUSREASONID = SA.FK_STATUSREASONID ORDER BY SR.STATUSREASONID DESC;
--42400157027 - 11054227, 11054166, 11054061

SELECT SR.STATUSREASONID, SA.FK_STATUSREASONID, SR.FK_TRANSACTIONID, SR.SOURCESYSTEM, SR.CODE, SA.ADDITIONALINFORMATION 
FROM STATUSREASON SR, STATUSREASON_ADDT_INF SA WHERE SR.STATUSREASONID = SA.FK_STATUSREASONID ORDER BY SR.STATUSREASONID DESC;