SELECT * FROM V_PAYMENT_OVERVIEW_TEST WHERE CREATIONDATETIME > SYSDATE-(15/24/60) ORDER BY TRANSACTIONSID DESC;
SELECT * FROM V_STRAKS_TEST;-- WHERE INFLIGHT_STATUS IN ('REJECTED');
------------------------------------------------------------------------------------------------
SELECT * FROM PRODUCT_FEATURE WHERE INITIATORBANKID IN ('2544','4201') AND PRODUCT IN ('Straks-2.0','Straks-2.1') AND IS_ACTIVE IN ('Y','N');
SELECT * FROM INSTANT_INFLIGHT_INFO WHERE STATUS NOT IN ('IN_PROGRESS') ORDER BY INFLIGHT_INFO_ID DESC;
SELECT * FROM INSTANT_INFLIGHT_INFO_ARCH ORDER BY INFLIGHT_INFO_ID DESC;
SELECT * FROM INSTANT_INWARD_TRANSACTION ORDER BY TRANSACTIONSID DESC;
SELECT * FROM INSTANT_INWARD_TRANS_ARCH ORDER BY CREATIONDATETIME DESC;
SELECT * FROM INWARD_STATUS_REASON ORDER BY INWARD_STATUSREASON_ID DESC;
SELECT * FROM INSTANT_INWARD_STATUSRSN_ARCH ORDER BY INWARD_STATUSREASON_ID DESC;
SELECT * FROM STATUSREASON SR, STATUSREASON_ADDT_INF SA WHERE SR.STATUSREASONID = SA.FK_STATUSREASONID ORDER BY SR.STATUSREASONID DESC;
------------------------------------------------------------------------------------------------
--ACTIVE TABLE: INSTANT_INFLIGHT_INFO, INSTANT_INWARD_TRANSACTION --> 11054399

SELECT INFLIGHT.TRANSACTIONID,INWARD.TRANSACTIONSID AS IN_TRANSACTIONSID,INFLIGHT.MSGID AS MESSAGEID, INFLIGHT.STATUS AS INFLIGHT_STATUS, 
INWARD.PAYMENTSTATUS AS IN_STATUS,INFLIGHT.DEBITBOOKINGID,INFLIGHT.CREDITBOOKINGID,INWARD.INTERBANK_SETTLEMENT_AMT AS IN_SETLMT_AMT, 
INWARD.INTERBANK_SETTLEMENT_CCY AS IN_SETLMT_CCY, INFLIGHT.DEBITACCOUNT,INFLIGHT.CREDITACCOUNT,INWARD.CUSTOMERID AS IN_CUSTOMERID,
INWARD.ENDTOENDID AS IN_ENDTOENDID, INFLIGHT.CREATIONDATETIME,INFLIGHT.INFLIGHT_INFO_ID AS INFLIGHT_INFO_ID,INFLIGHT.DIRECTION AS DIRECTION,
INFLIGHT.CLEARING_CYCLE, INFLIGHT.STATUSCHANGETIME,INFLIGHT.PROCESSING_BIC,INWARD.DEBTOR_AGENT_BIC AS IN_DBTR_AGNT_BIC,
INWARD.CREDITOR_AGENT_BIC AS IN_CRDT_AGNT_BIC,INFLIGHT.INTERBANKSETTLEMENTDATE AS OUT_STLMT_DATE,INWARD.INTERBANK_SETTLEMENT_DATE AS IN_STLMT_DATE,
INWARD.SETTLEMENT_METHOD AS IN_STLMT_METHOD,INWARD.SETTLEMENT_CLEARING_SYSTEM_CD AS IN_STLMT_CLRSYS,INWARD.LOCAL_INSTRUMENT AS IN_LOCL_INSTR,
INWARD.CHARGEBEARER AS IN_CHARGEBEARER,INWARD.ACCEPTANCE_DATE_TIME AS IN_ACCEPTANCE_DATE_TIME FROM INSTANT_INFLIGHT_INFO INFLIGHT 
LEFT OUTER JOIN INSTANT_INWARD_TRANSACTION INWARD ON INFLIGHT.MSGID = INWARD.MSGID ORDER BY INFLIGHT.INFLIGHT_INFO_ID DESC;
------------------------------------------------------------------------------------------------
--OUTWARD PAYMENT REJECT REASON

SELECT INSTANT.INFLIGHT_INFO_ID,INSTANT.TRANSACTIONID,INSTANT.STATUS,SR.CODE,SA.ADDITIONALINFORMATION, INSTANT.CREATIONDATETIME,INSTANT.DIRECTION,
INSTANT.DEBITACCOUNT,INSTANT.MSGID FROM INSTANT_INFLIGHT_INFO INSTANT, STATUSREASON SR, STATUSREASON_ADDT_INF SA
WHERE SR.FK_TRANSACTIONID = INSTANT.TRANSACTIONID AND SR.STATUSREASONID = SA.FK_STATUSREASONID ORDER BY INSTANT.CREATIONDATETIME DESC;
------------------------------------------------------------------------------------------------
--INWARD PAYMENT REJECT REASON

SELECT INSTANT.INFLIGHT_INFO_ID,INSTANT.TRANSACTIONID,INSTANT.DIRECTION,INSTANT.MSGID,INSTANT.DEBITACCOUNT,INSTANT.STATUS,SR.CODE,SA.ADDITIONALINFORMATION,
INSTANT.CREATIONDATETIME FROM INSTANT_INFLIGHT_INFO_ARCH INSTANT, STATUSREASON SR, STATUSREASON_ADDT_INF SA WHERE INSTANT.STATUS = 'REJECTED'
AND SR.FK_TRANSACTIONID = INSTANT.TRANSACTIONID AND SR.STATUSREASONID = SA.FK_STATUSREASONID ORDER BY SR.STATUSREASONID DESC;
------------------------------------------------------------------------------------------------
--ARCHIVE TABLE: INSTANT_INFLIGHT_INFO_ARCH, INSTANT_INWARD_TRANS_ARCH

SELECT INFLIGHT_ARCH.TRANSACTIONID,INWARD_ARCH.TRANSACTIONSID AS C_TRANSACTIONSID,INFLIGHT_ARCH.MSGID AS MESSAGEID, INFLIGHT_ARCH.STATUS AS INFLIGHT_STATUS, 
INWARD_ARCH.PAYMENTSTATUS AS IN_STATUS,INFLIGHT_ARCH.DEBITBOOKINGID,INFLIGHT_ARCH.CREDITBOOKINGID,INWARD_ARCH.INTERBANK_SETTLEMENT_AMT AS IN_SETLMT_AMT, 
INWARD_ARCH.INTERBANK_SETTLEMENT_CCY AS IN_SETLMT_CCY, INFLIGHT_ARCH.DEBITACCOUNT,INFLIGHT_ARCH.CREDITACCOUNT,INWARD_ARCH.CUSTOMERID AS IN_CUSTOMERID,
INWARD_ARCH.ENDTOENDID AS IN_ENDTOENDID, INFLIGHT_ARCH.CREATIONDATETIME,INFLIGHT_ARCH.INFLIGHT_INFO_ID AS INFLIGHT_ID,INFLIGHT_ARCH.DIRECTION AS DIRECTION,
INFLIGHT_ARCH.CLEARING_CYCLE, INFLIGHT_ARCH.STATUSCHANGETIME,INFLIGHT_ARCH.PROCESSING_BIC,INWARD_ARCH.DEBTOR_AGENT_BIC AS IN_D_AGNT_BIC,
INWARD_ARCH.CREDITOR_AGENT_BIC AS IN_C_AGNT_BIC,INFLIGHT_ARCH.INTERBANKSETTLEMENTDATE AS D_STLMT_DATE,INWARD_ARCH.INTERBANK_SETTLEMENT_DATE AS C_STLMT_DATE,
INWARD_ARCH.SETTLEMENT_METHOD AS IN_STLMT_METHOD,INWARD_ARCH.SETTLEMENT_CLEARING_SYSTEM_CD AS IN_STLMT_CLRSYS,INWARD_ARCH.LOCAL_INSTRUMENT AS IN_LOCL_INSTR,
INWARD_ARCH.CHARGEBEARER AS IN_CHARGEBEARER,INWARD_ARCH.ACCEPTANCE_DATE_TIME AS IN_ACCEPTANCE_DATE_TIME FROM INSTANT_INFLIGHT_INFO_ARCH INFLIGHT_ARCH 
LEFT OUTER JOIN INSTANT_INWARD_TRANS_ARCH INWARD_ARCH ON INFLIGHT_ARCH.MSGID = INWARD_ARCH.MSGID ORDER BY INFLIGHT_ARCH.INFLIGHT_INFO_ID DESC;