SELECT TRANSACTIONSID,ENDTOENDID,
PAYMENT_REF FROM HST_TRANSACTIONS 
WHERE INITIATORBANKID=4201 
AND FK_PROCESSINGLINEID=57
ORDER BY TRANSACTIONSID DESC
FETCH FIRST 1 ROWS ONLY
;
SELECT TRANSACTIONSID,ENDTOENDID,
PAYMENT_REF FROM TRANSACTIONS 
WHERE INITIATORBANKID=4201 
AND FK_PROCESSINGLINEID=57 AND 
PAYMENTSTATUS IN ('WFRE','TERE','PEPE','RFCA')
ORDER BY TRANSACTIONSID DESC
FETCH FIRST 1 ROWS ONLY
;