SELECT * FROM V_AUTHORISATION WHERE ROLETYPE  ='EIER' --AND ACCOUNTNUMBER NOT IN (SELECT AGREEMENTACCOUNTNUMBER FROM STO_AGREEMENT)
AND CUSTOMERID IN
  (SELECT CUSTOMERID
  FROM V_AUTHORISATION
  WHERE CUSTBANKID       ='3890'
  AND LENGTH(CUSTOMERID) =11
  GROUP BY CUSTOMERID
  HAVING COUNT(CUSTOMERID) > 1
  )
ORDER BY CUSTOMERID
FETCH FIRST 10 ROW ONLY;