    SELECT * --MESSAGEID,MARKETTYPE,INITIATORBANKID,CUSTOMERID,MESSAGEIDENTIFICATION,COVERAGE_CONTROL,DAYS_TO_LAFU,DAILY_REPORT_LAFU
    FROM MESSAGE WHERE CREATIONDATETIME > (SYSDATE - 24/60) ORDER BY MESSAGEID DESC;
-------------------------------------------------------------------------
    SELECT * --PAYMENTINFOID,FK_MESSAGEID,BATCHBOOKING,CATEGORYPURPOSECODE,INSTRUCTIONPRIORITY,SERVICELEVEL,INITIATORBANKID,DEBETACCOUNTNO
    FROM PAYMENTINFO ORDER BY PAYMENTINFOID DESC;
-------------------------------------------------------------------------
    SELECT * --TRANSACTIONSID,ENDTOENDID,INITIATORBANKID,FK_PAYMENTINFOID,INSTRUCTEDAMOUNT,PAYMENTSTATUS,ISPC,FK_PROCESSINGLINEID,RELEASEDATE
    FROM TRANSACTIONS WHERE TRANSACTIONSID < '1000999999' ORDER BY TRANSACTIONSID DESC;
-------------------------------------------------------------------------INSTRUCTIONPRIORITY