/* MIGRATE FIELDS FROM REGULATORYREPORTING_DTLS TO REGULATORYREPORTING_DTLS_INFO */   
DECLARE
   CURSOR REGULATORYREPORTING_DTLS_CUR IS
           SELECT RGLTRYRPTGDTLSID,INFORMATION FROM REGULATORYREPORTING_DTLS;
   TYPE REG_REPORTING_DTLS_CUR_TYPE IS RECORD (
          RGLTRYRPTGDTLSID    NUMBER(18,0),
          INFORMATION         VARCHAR2(70 CHAR)
      );   
   TYPE REG_REP_DTLS_CUR_TYPE_COLL IS TABLE OF REG_REPORTING_DTLS_CUR_TYPE INDEX BY BINARY_INTEGER; 
   V_REGREP_COLL REG_REP_DTLS_CUR_TYPE_COLL ;  
   V_LIMIT       NUMBER := 10000;       
BEGIN
   OPEN REGULATORYREPORTING_DTLS_CUR;
   LOOP
   FETCH REGULATORYREPORTING_DTLS_CUR BULK COLLECT INTO V_REGREP_COLL LIMIT V_LIMIT;
   EXIT WHEN V_REGREP_COLL.COUNT = 0;
      FORALL I IN V_REGREP_COLL.FIRST..V_REGREP_COLL.LAST
         INSERT INTO REGULATORYREPORTING_DTLS_INFO(RGLTRYRPTGDTLSINFOID,FK_RGLTRYRPTGDTLSID,INFORMATION,LINE_NUMBER)
         VALUES (REG_REPORTING_DTLS_INFO_ID_SEQ.NEXTVAL,V_REGREP_COLL(I).RGLTRYRPTGDTLSID,V_REGREP_COLL(I).INFORMATION,1);
         COMMIT;
   END LOOP;
   CLOSE REGULATORYREPORTING_DTLS_CUR;
END;
/