SELECT CUSTBANKID,CUSTOMERTYPE,VIPCODE,CUSTOMERID,ACCOUNTNUMBER,CURRENCY,ROLETYPE,ROLEBANKID,CLOSED,BLOCKEDFORCREDIT,BLOCKEDFORDEBIT,
VALIDTO,COMPANYNAME,IBANACCOUNTNUMBER FROM V_AUTHORISATION WHERE 1=1 --AND CURRENCY = 'EUR' 
AND CUSTBANKID='9021' --AND ACCOUNTNUMBER LIKE '40680113361'  --AND CURRENCY = 'EUR' 
--AND VIPCODE IN ('1','2','3','4','5','6','7','8','9') 986438297/42123118434 and 07039619126/42123118078 and 28115000014/42123119376
--AND CUSTOMERID LIKE '0106%'       --AND ACCOUNTNUMBER IN ('42021430580')      --AND VIPCODE <> 0      --ORDER BY ACCOUNTNUMBER DESC
;--=============================================================================
select * from V_AUTHORISATION
;--=============================================================================
SELECT * FROM AUTH_ACTIVE_DATASET WHERE STATUS='CURRENT';
SELECT * FROM AUTH_CUSTOMERDATA_SET2 WHERE CUSTBANKID= '3625';
SELECT * FROM AUTH_ACCOUNTDATA_SET2 WHERE ACCOUNTNUMBER LIKE '25%'; --AND CURRENCY='NOK';
SELECT * FROM AUTH_ROLEDATA_SET2 WHERE ROLEBANKID='3625'
;--=============================================================================
SELECT CUSTBANKID,CUSTOMERID,ACCOUNTNUMBER,CURRENCY,VIPCODE FROM V_AUTHORISATION WHERE VIPCODE<>0 AND ROLETYPE='EIER' AND CUSTBANKID IN('4201'); --FETCH FIRST 5 ROW ONLY
SELECT * FROM V_AUTHORISATION WHERE VIPCODE<>0 AND ROLETYPE='EIER' AND CUSTBANKID IN('4201');
SELECT DISTINCT VIPCODE FROM V_AUTHORISATION;