--=========================================================================================================
SELECT V.BANKORGID,V.MARKETTYPE,V.AGREEMENTID,V.USERID,V.CHANNEL,V.ACCOUNTNUMBER,V.CURRENCYCODE,V.ACCOUNTTYPENAME,V.BIC,V.RBSUSERID,V.APPROVALLIMIT,V.REGISTERLIMIT,V.MONTHLYLIMIT,
V.TRANSACTIONLIMIT,V.FIRSTNAME,V.LASTNAME,V.ACCOUNTROLENAME FROM V_AUTH_USERINFO V WHERE 1=1 AND V.MARKETTYPE='PM' AND V.CHANNEL = 'INT' 
--  AND V.BANKORGID IN ('2544')
--  AND V.USERID LIKE '28059101953%'
--  AND V.USERID IN ('14107005111','26067412051','26107019579');
  AND V.ACCOUNTNUMBER LIKE '42020261298%'
--  AND CURRENCYCODE IN ('NOK')
ORDER BY V.ACCOUNTNUMBER DESC,V.USERID DESC
;--========================================================================================================
SELECT DISTINCT ACCOUNTNUMBER FROM V_AUTH_USERINFO V WHERE V.MARKETTYPE='PM' AND V.CHANNEL = 'INT'
AND V.BANKORGID IN ('3625') AND CURRENCYCODE IN ('NOK') AND V.ACCOUNTNUMBER LIKE '3625%'
;--========================================================================================================
SELECT KUNDENR AS CUSTOMER,BRUKERID AS USERID,KONTONR AS ACCOUNT,INSTITUTION_CODE AS BANK,DEFAULT_TJENESTER AS ROLE,VALUTAKODE AS CCY FROM V_AUT_AU9 WHERE INSTITUTION_CODE='3625';
SELECT BRUKERID AS USERID, SELSKAP_ID, BRUKER_TYPE, BRUKERNAVN, BRUKER_KUNDENR AS CUSTOMER, FORETAK_KUNDENR, INSTITUTION_CODE AS BANK FROM V_AUT_AU1 WHERE INSTITUTION_CODE='3625' 
  AND BRUKERID IN (SELECT BRUKERID FROM V_AUT_AU9 WHERE V_AUT_AU9.KUNDENR=V_AUT_AU1.BRUKER_KUNDENR)
;--========================================================================================================