SELECT * FROM V_AUTHORISATION WHERE CUSTBANKID='4201';

SELECT CUSTOMERID,CUSTBANKID,ACCOUNTNUMBER,CURRENCY,CLOSED,BLOCKED,BLOCKEDFORCREDIT,BLOCKEDFORDEBIT,BEINGCLOSED FROM V_AUTHORISATION WHERE 1=1
AND CUSTBANKID='2544'
AND CURRENCY = 'NOK'
--AND BLOCKED = 'Y' AND ACCOUNTNUMBER IN ('42010254404','42010195505','')
--AND CLOSED = 'Y'
--AND BLOCKEDFORDEBIT = 'Y'
--AND BLOCKEDFORCREDIT = 'Y'
--AND BEINGCLOSED = 'Y'
;