-- CREATE OR DROP A VIEW "V_PAYMENT_OVERVIEW_TEST"
--==============================================================================
SELECT * FROM V_PAYMENT_OVERVIEW_TEST;
DROP VIEW V_PAYMENT_OVERVIEW_TEST;
COMMIT;
--==============================================================================
CREATE OR REPLACE VIEW V_PAYMENT_OVERVIEW_TEST AS
  SELECT M.MESSAGEID,
    P.PAYMENTINFOID,
    T.TRANSACTIONSID,
    T.PAYMENT_REF,
    T.ENDTOENDID,
    T.PAYMENTTYPE,
    T.FK_PROCESSINGLINEID,
    D.INSERT_TIME,
    T.PAYMENTSTATUS,
    T.INITIATORBANKID,
    T.PROCESSINGBANKORGID,
    T.INSTRUCTEDAMOUNT,
    T.DEBITCOUNTERVALUEAMT,
    T.DEBITCOUNTERVALUECCY,
    T.RELEASEDATE,
    M.CREATIONDATETIME,
    T.STATUSCHANGETIME,
    R.RESERVATION_TYPE,
    T.DEBIT_BOOKING_ID,
    SE.SETTLEMENTID,
    SE.BOOKINGDATE,
    M.MARKETTYPE,
    M.AGREEMENTID,
    M.INITIATORID,
    M.CUSTOMERID,
    P.DEBETACCOUNTNO,
    A.APPROVERIDENTIFIER AS APPROVER,
    M.ORIGINALCHANNEL,
    T.RISKSTATUS,
    SCA.EVENT_SOURCE,
    SCA.SCA_PERFORMED,
    SCA.SCA_LAST_PERFORMED,
    SCA.EXEMPTION_TYPE,
    SCA.EVENT_TIME,
    AC.OTHER_ID        AS CREDITOR_BBAN,
    AC.IBAN            AS CREDITOR_IBAN,
    T.AGREEMENTID      AS SO_AGREEMENTID,
    T.AGREEMENTVERSION AS SO_AGREEMENTVERSION,
    M.PAINVERSION,
    T.SKKOTYPE,
    M.MESSAGEIDENTIFICATION,
    P.PMTINFOID,
    T.INSTRUCTIONID,
    M.ORIGINALFORMAT,
    T.ISPC,
    P.CATEGORYPURPOSECODE,
    P.SERVICELEVEL,
    P.INSTRUCTIONPRIORITY,
    T.RECEIPTORDER,
    T.FIRSTLACKOFFUNDSMESSAGESENT,
    T.SEPA,
    T.HIDDEN,
    T.WB_FLAG,
    T.PRIORITIZED,
    T.FORCE_FUND,
    T.REQUESTEDEXECUTIONDATE,
    M.TPPID,
    M.TPPNAME,
    L.LASTOFDAY_COUNTER AS LAFU_COUNT,
    I.INSTRUCTIONTYPE,
    I.ADDITIONALINFO,
    I.INSTRUCTIONFUNCTION,
    R.RESERVATIONREFERENCE,
    REGREPDET.CODE               AS REGULATORYCODE,
    REGREPDET.INFORMATION        AS REGULATORYINFO,
    DEBTOR_PARTY.PRVTID_OTHER_ID AS DEBTORSSN,
    DEBTOR_PARTY.NAME            AS DEBTORNAME,
    DEBTOR_PARTY.POSTALADDRESSID,
    DEBTOR_PARTY.ADDRESSLINE1,
    DEBTOR_PARTY.ADDRESSLINE2,
    DEBTOR_PARTY.ADDRESSLINE3,
    DEBTOR_PARTY.ADDRESSLINE4,
    DEBTOR_PARTY.POSTCODE,
    DEBTOR_PARTY.TOWNNAME,
    DEBTOR_PARTY.COUNTRY,
    DEBTOR_ACCOUNT.IBAN  AS DEBTAR_IBAN,
    DEBTOR_AGENT.NAME    AS DEBTAR_AGENT_NAME,
    DEBTOR_AGENT.BICFI   AS DEBTAR_AGENT_BIC,
    CREDITOR_AGENT.BICFI AS CREDITOR_AGENT_BIC,
    CREDITOR_AGENT.NAME  AS CREDITOR_AGENT_NAME
  FROM TRANSACTIONS T
  INNER JOIN PAYMENTINFO P                              ON T.FK_PAYMENTINFOID=P.PAYMENTINFOID
  INNER JOIN MESSAGE M                                  ON M.MESSAGEID=P.FK_MESSAGEID
  LEFT OUTER JOIN SCA_EVENTLOG SCA                      ON SCA.FK_TRANSACTIONSID=T.TRANSACTIONSID   --  Enable SCA if code is present
  LEFT OUTER JOIN LACKOFFUNDSTRANSACTIONS L             ON L.FK_TRANSACTIONSID=T.TRANSACTIONSID
  LEFT OUTER JOIN INSTRUCTIONS I                        ON I.FK_TRANSACTIONSID=T.TRANSACTIONSID
  LEFT OUTER JOIN APPROVER A                            ON A.FK_TRANSACTIONSID=T.TRANSACTIONSID
  LEFT OUTER JOIN RESERVATION_DETAILS R                 ON R.FK_TRANSACTIONSID=T.TRANSACTIONSID
  LEFT OUTER JOIN ACCOUNT_CREDITOR AC                   ON AC.FK_TRANSACTIONSID=T.TRANSACTIONSID
  LEFT OUTER JOIN DIRECT_RELEASE_UNPROCESSED_TXN D      ON D.TRANSACTIONSID=T.TRANSACTIONSID
  LEFT OUTER JOIN AGENT_PAYMENTINFO DEBTOR_AGENT        ON DEBTOR_AGENT.FK_PAYMENTINFOID = P.PAYMENTINFOID      AND DEBTOR_AGENT.FK_AGENTTYPEID  =3            
  LEFT OUTER JOIN ACCOUNT_DEBTOR DEBTOR_ACCOUNT         ON DEBTOR_ACCOUNT.FK_PAYMENTINFOID = P.PAYMENTINFOID    AND DEBTOR_ACCOUNT.FK_ACCOUNTTYPEID=1
  LEFT OUTER JOIN PARTY_DEBTOR DEBTOR_PARTY             ON DEBTOR_PARTY.FK_PAYMENTINFOID = P.PAYMENTINFOID      AND DEBTOR_PARTY.FK_PARTYTYPEID  =2
  LEFT OUTER JOIN AGENT_TRANS CREDITOR_AGENT            ON CREDITOR_AGENT.FK_TRANSACTIONSID=T.TRANSACTIONSID    AND CREDITOR_AGENT.FK_AGENTTYPEID  =2
  LEFT OUTER JOIN REGULATORYREPORTING REGREP            ON REGREP.FK_TRANSACTIONSID = T.TRANSACTIONSID
  LEFT OUTER JOIN REGULATORYREPORTING_DTLS REGREPDET    ON REGREPDET.FK_RGLTRYRPTGID = REGREP.RGLTRYRPTGID
  LEFT OUTER JOIN SETTLEMENT SE                         ON SE.FK_TRANSACTIONSID          = T.TRANSACTIONSID
  WHERE TRUNC(M.CREATIONDATETIME) >= SYSDATE-400 ORDER BY M.CREATIONDATETIME DESC, T.TRANSACTIONSID DESC;