-- CREATE OR DROP A VIEW "V_PAYMENT_OVERVIEW_TEST"
--==============================================================================
SELECT * FROM V_STRAKS_TEST;
DROP VIEW V_STRAKS_TEST;
COMMIT;
--==============================================================================
CREATE OR REPLACE VIEW V_STRAKS_TEST AS
    SELECT
        INFLIGHT_ARCH.DIRECTION,
        INFLIGHT_ARCH.TRANSACTIONID,
        HST_TRANSACTION.FK_PROCESSINGLINEID AS PROC_LINE_ID,
        HST_TRANSACTION.INITIATORBANKID AS ORG_ID,
        INFLIGHT_ARCH.STATUS AS INFLIGHT_STATUS,
        INFLIGHT_ARCH.DEBITBOOKINGID,
        INFLIGHT_ARCH.CREDITBOOKINGID,
        INWARD_TRANS_ARCH.TRANSACTIONSID AS IN_TRANSACTIONSID,
        INWARD_TRANS_ARCH.PAYMENTSTATUS AS IN_STATUS,
        INFLIGHT_ARCH.MSGID AS MESSAGEID,
        INWARD_TRANS_ARCH.INTERBANK_SETTLEMENT_AMT AS IN_SETLMT_AMT,
        INWARD_TRANS_ARCH.INTERBANK_SETTLEMENT_CCY AS IN_SETLMT_CCY,
        INFLIGHT_ARCH.DEBITACCOUNT,
        INFLIGHT_ARCH.CREDITACCOUNT,
        HST_TRANSACTION.INSTRUCTIONID,
        INWARD_TRANS_ARCH.CUSTOMERID AS IN_CUSTOMERID,
        HST_TRANSACTION.ENDTOENDID AS OUT_ENDTOENDID,
        INWARD_TRANS_ARCH.ENDTOENDID AS IN_ENDTOENDID,
        INFLIGHT_ARCH.CREATIONDATETIME,
        INFLIGHT_ARCH.INFLIGHT_INFO_ID AS INFLIGHT_INFO_ID,
        INFLIGHT_ARCH.CLEARING_CYCLE,
        INFLIGHT_ARCH.STATUSCHANGETIME,
        INFLIGHT_ARCH.PROCESSING_BIC,
        INWARD_TRANS_ARCH.DEBTOR_AGENT_BIC AS IN_DBTR_AGNT_BIC,
        INWARD_TRANS_ARCH.CREDITOR_AGENT_BIC AS IN_CRDT_AGNT_BIC,
        INFLIGHT_ARCH.INTERBANKSETTLEMENTDATE AS OUT_STLMT_DATE,
        INWARD_TRANS_ARCH.INTERBANK_SETTLEMENT_DATE AS IN_STLMT_DATE,
        INWARD_TRANS_ARCH.SETTLEMENT_METHOD AS IN_STLMT_METHOD,
        INWARD_TRANS_ARCH.SETTLEMENT_CLEARING_SYSTEM_CD AS IN_STLMT_CLRSYS,
        INWARD_TRANS_ARCH.LOCAL_INSTRUMENT AS IN_LOCL_INSTR,
        INWARD_TRANS_ARCH.CHARGEBEARER AS IN_CHARGEBEARER,
        INWARD_TRANS_ARCH.ACCEPTANCE_DATE_TIME AS IN_ACCEPTANCE_DATE_TIME,
        SR.CODE,
        SA.ADDITIONALINFORMATION,
        INWARD_REASON_ARCH.STATUSREASON_CODE,
        INWARD_REASON_ARCH.STATUSREASON_DESC
    FROM INSTANT_INFLIGHT_INFO_ARCH INFLIGHT_ARCH
        LEFT OUTER JOIN INSTANT_INWARD_TRANS_ARCH INWARD_TRANS_ARCH ON INFLIGHT_ARCH.MSGID = INWARD_TRANS_ARCH.MSGID
        LEFT OUTER JOIN HST_TRANSACTIONS HST_TRANSACTION ON INFLIGHT_ARCH.TRANSACTIONID = HST_TRANSACTION.TRANSACTIONSID
        LEFT OUTER JOIN TRANSACTIONS TRANSACTION ON INFLIGHT_ARCH.TRANSACTIONID = TRANSACTION.TRANSACTIONSID
        LEFT OUTER JOIN INSTANT_INWARD_STATUSRSN_ARCH INWARD_REASON_ARCH ON INWARD_REASON_ARCH.TRANSACTIONSID = INWARD_TRANS_ARCH.TRANSACTIONSID
        LEFT OUTER JOIN STATUSREASON SR ON SR.FK_TRANSACTIONID = INFLIGHT_ARCH.TRANSACTIONID
        LEFT OUTER JOIN STATUSREASON_ADDT_INF SA ON SR.STATUSREASONID = SA.FK_STATUSREASONID
    WHERE INFLIGHT_ARCH.STATUS IN ('REJECTED','COMPLETED')
    ORDER BY INFLIGHT_ARCH.INFLIGHT_INFO_ID DESC;