SELECT V.*, WB.WB_HIT_ID, WB.STATUS, WB.VISIBLE_TO_END_USER, WB.INTERNAL_DESCRIPTION, WB.FREE_TEXT,WB.NAME
FROM V_PAYMENT_OVERVIEW_TEST V LEFT OUTER JOIN WB_HIT WB ON  WB.FK_TRANSACTIONSID=V.TRANSACTIONSID
WHERE 1=1 --AND TRUNC(CREATIONDATETIME) >= SYSDATE-1
--AND INITIATORBANKID IN ('4201')
--AND FK_PROCESSINGLINEID IN ('3')
--AND V.ENDTOENDID LIKE '685%'
--AND MESSAGEIDENTIFICATION LIKE 'B2B%'
--AND TRANSACTIONSID IN ('112575') --AND PAYMENT_REF='402845'
--AND DEBETACCOUNTNO IN ('42010207511') --AND PAYMENTSTATUS NOT IN ('VALI','REJC','TBAP','CANC')
;
--=============================================================================